services:
  db:
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langdevblog
    ports:
      - "5432:5432"

  # For testing email sending during development
  mailtutan:
    image: mailtutan/mailtutan:latest
    ports:
      - "1080:1080"
      - "1025:1025"
