CREATE TABLE invite (
  id BIGSERIAL PRIMARY KEY,
  inviter_id BIGSERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ
);

CREATE INDEX ix_invite_token ON invite USING HASH(token);
